### ISSUE TITLE
[skdb] "Access key" or "user ID"?

### ISSUE THREAD

**Issue by ltique** [SkipLabs/skip#119]
The CLI talks about "access keys":

```
$ npx skdb --help
Usage: bin/skdb-cli [--help]                      
    [--access-key <key>]  -- Access key to use. Default: first specified in credentials file.
```

but `skdb_users` uses "userID":

```
root@ws://localhost:3586/chat-app> .schema
CREATE TABLE skdb_users (
  userID TEXT PRIMARY KEY,
  privateKey TEXT NOT NULL
);
```

I guess "user ID" is now the preferred terminology?

**Comment by gregsexton** [comment]
Yeah we should converge. I avoided 'user' in the auth because you don't choose your id, it's generated. This is a common pattern with web services and they usually call this 'access key'. But semantically this equates to a user of skdb and internally we prefer the term user as that makes things clearer in that context.

**Comment by beauby** [comment]
Closing skdb-specific issues as skdb in its current form is being deprecated.
