### ISSUE TITLE
Cannot insert a generated id using a select

### ISSUE THREAD

**Issue by gregsexton** [SkipLabs/skip#164]
I want to do this:

```
INSERT INTO pk_single_row_hist SELECT local_sequence_number(), datetime(), client, value FROM pk_single_row;
```

But I cannot.

```
Error: line 1, character 0:
local_sequence_number expects a string literal
```

This is true of id() and some other things that seem to behave differently if they're an expression in a select's col expression list or an insert's value list.

**Comment by gregsexton** [comment]
A quick peek at the code suggests that id is not just a function - probably should be?

**Comment by jberdine** [comment]
I need to chase through the INSERT statements other than the VALUES form, but currently all the generation is done when evaluating the values to INSERT. Occurrences in general expressions only look up existing associations of string keys to the values generated during INSERT...VALUES. I guess that the addition of other INSERT forms has slipped in some new cases that used to be impossible.

I don't know that this can be implemented as a normal function, since it needs to manage backing state that has per-transaction scope.

**Comment by gregsexton** [comment]
I think I'd be pretty happy with it behaving as a function in the select case where it's ok with an optional input. Without the input, it just returns a new id each time.

**Comment by jberdine** [comment]
And if it is given an argument that has not previously been associated to a value, error out? Or would the right thing be to generate a new association there too? I need to check the feasibility of managing per-transaction state at that point, maybe possible, not sure.

**Comment by gregsexton** [comment]
Error seems reasonable to me. The semantics then are pretty clear: it's retrieval of an id for a value, but none is like a unique value each time.
