### ISSUE TITLE
Swap out websockets for Server-Sent Events

### ISSUE THREAD

**Issue by bennostein** [SkipLabs/skip#472]

**Comment by bitnom** [comment]
> No description provided.

I'm curious to know why this was done and if it is or should be configurable, to swap back to websockets.

**Comment by jberdine** [comment]
To use websockets we had a custom protocol to establish the connection and this meant we needed a skip-specific client-side package.  We thought server side events were preferable because it uses standard http/2, and any desired implementation of an SSE client, in any language, can be used.

But let us know if there are some use cases where you think websockets are a better option vs SSE.
